#![allow(unused)]

fn main() {
    
    // Panicking will cause your program to print out an error message and exit abruptly
    // Panic macro
    // panic!("Somethign went wrong");

    let numbers = vec!["one", "two", "three"];
    // Panic: index out of bounds (there is no forth element)
    // println!("{}", numbers[3]);
    println!("Hello, world!");

}